name: Updated

on:
  push

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Sets up R
      uses: r-lib/actions/setup-r@v2
    - run: pip install rpy2==3.5.12
    - run: python3 --version
    - run: pip list
    - run: ls -la
    - run: Rscript -e "install.packages('renv')" && Rscript -e 'renv::install()'
    # - name: Installs packages declared in DESCRIPTION
    #   uses: r-lib/actions/setup-r-dependencies@v2
    #   with:
    #     cache-version: 2
    #     extra-packages: |
    #       any::ggplot2
    - run: python3 scripts/main.py
