[keys]

chave_execucao = [
    "uo_cod",
    "acao_cod",
    "grupo_cod",
    "iag_cod",
    "fonte_cod",
    "ipu_cod",
    "elemento_item_cod_cod",
    "contrato_cod"
]

chave_credito = [
    "uo_cod",
    "acao_cod",
    "grupo_cod",
    "iag_cod",
    "fonte_cod",
    "ipu_cod",
    "elemento_item_cod"
]

chave_receita = [
    "uo_cod",
    "fonte_cod"
]


[data.execucao]

"path" = "data/exec.csv"
"resource_name" = "execucao"
"key_name" = "chave_execucao"

[data.rp]

"path" = "data/rp.csv"
"resource_name" = "rp"
"key_name" = "chave_execucao"


[data.cota]

"path" = "data/cota.csv"
"resource_name" = "cota"
"key_name" = "chave_credito"

[data.credito]

"path" = "data/credito.csv"
"resource_name" = "credito"
"key_name" = "chave_credito"


[data.receita]

"path" = "data/receita.csv"
"resource_name" = "receita"
"key_name" = "chave_receita"

[data.obz]

"path" = "data/obz.csv"
"resource_name" = "obz"
"key_name" = "chave_credito"
