[keys]

chave_execucao = [
    "uo_cod",
    "acao_cod",
    "grupo_cod",
    "iag_cod",
    "fonte_cod",
    "ipu_cod",
    "elemento_item_cod",
    "contrato"
]

chave_credito = [
    "uo_cod",
    "acao_cod",
    "grupo_cod",
    "iag_cod",
    "fonte_cod",
    "ipu_cod"   
]

chave_cota = [
    "uo_cod",
    "acao_cod",
    "grupo_cod",
    "iag_cod",
    "fonte_cod",
    "ipu_cod",
    "elemento_item_cod"   
]

chave_receita = [
    "uo_cod",
    "fonte_cod"
]


[data.execucao]

"path" = "datapackages/execucao/datapackage.json"
"resource_name" = "execucao"
"key_name" = "chave_execucao"

[data.rp]

"path" = "datapackages/rp/datapackage.json"
"resource_name" = "rp"
"key_name" = "chave_execucao"


[data.cota]

"path" = "datapackages/cota/datapackage.json"
"resource_name" = "cota"
"key_name" = "chave_cota"

[data.credito]

"path" = "datapackages/credito/datapackage.json"
"resource_name" = "credito"
"key_name" = "chave_credito"


[data.receita]

"path" = "datapackages/receita/datapackage.json"
"resource_name" = "receita"
"key_name" = "chave_receita"

[data.obz]

"path" = "datapackages/obz/datapackage.json"
"resource_name" = "obz"
"key_name" = "chave_cota"
